sudo: required
services:
  - docker

before_install:
  - docker build -t noalistic/birdboard-test -f Dockerfile .
script:
  - docker run noalistic/birdboard-test vendor/bin/phpunit

after_success:
  - docker build -t papiyinks/birdboard-app .
  # - docker build -t noalistic/birdboard-nginx -f Dockerfile.nginx .
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push noalistic/birdboard-app
  # - docker push noalistic/birdboard-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: birdboard-docker
  env: BirdboardDocker-env
  bucket_name: elasticbeanstalk-us-east-2-946065250109
  bucket_path: docker-birdboard
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
